### ISSUE TITLE
upgrading splunk using the version field on the top of an earlier managed version

### ISSUE THREAD

**Issue by RampentPotato** [jorritfolmer/puppet-splunk#16] opened 2017-07-27 23:09 UTC
**Issue:**
When using the version parameter as a mean to upgrade to a newer version of splunk. The install completes but Splunk will not automatically start and puppet reports will contain errors.

Puppet installs the new version Splunk but it will not start resulting errors in the host report.

**Work around: (Tested on CentOS on  simple all-in-one Splunk install)**
Run "systemctl stop puppet" to  temporarily stop puppet from running

Run "./$SPLUNKHOME/splunk/bin/splunk version"
This will prompt you to accept the general terms and conditions of the new version, then prompt you to perform a upgrade/migration. Allow this to complete.

Run "./$SPLUNKHOME/splunk/bin/splunk version" again you should be presented with the updated version as expected.

Run "systemctl start puppet" to restart the Puppet agent.
Run "puppet agent -t" (assuming it hasn't already started)

Puppet will perform some remaining actions and start Splunk

Splunk should now be accessible and you should not see any more errors in the host report.

Any previous data (custom indexes and data) should still exist and be accessible.

@jorritfolmer - Great module btw.

**Comment by jorritfolmer** [comment] 2017-07-29 07:45
Thanks! I'll take a look at this.

**Comment by jorritfolmer** [comment] 2017-08-18 10:42
Fixed in most recent version!

Note that in clustered environments, you have to upgrade the instances in a specific order.
This extra orchestration is not taken care of here. Puppet does support application orchestration, however this is a Puppet Enterprise feature.

**Comment by RampentPotato** [comment] 2017-08-21 03:54
Hi,

Tested this today,  performs the upgrade aok, but leaves the service as Active [exited], restarting via systemctl restart splunk fixes it and its ok thereafter.

I will do some more testing to make sure its not something I am doing. ;o

RP.

**Comment by RampentPotato** [comment] 2017-08-21 04:29
Retested.
After the host file is updated to reference a newer version and the puppet agent run.
Puppet detects the mismatch and installs the new version of the top. At the end of the puppet run the splunk service is left as Active [Exited] and splunk is not avaiable fro mthe web gui.
A further puppet agent run updates the permissions on the passwd file, but does not restart the splunk service.
Further agent runs do nothing.

If the host is rebooted the puppet agent runs automatically, detects that splunk isn't running and restarts it.
splunk is now available.

**Comment by jorritfolmer** [comment] 2017-08-21 09:36
First of all, are you managing the running state in puppet with the `service` parameter?
Because by default the splunk module doesn't manage the running state because it will really break things in clustered environments.

To enable state management include the service parameter, for example:

```
 class { 'splunk':
    httpport           => 8000,
    kvstoreport        => 8191,
    inputport          => 9997,
    service      => {
      ensure     => running,
      enable     => true,
    }
  }
```

However, this doesn't work after updating because the RPM issues a direct "splunk stop" without using systemctl or init script. So according to systemd it is active. For Puppet and systemd everything is fine, and Splunk is not started after an upgrade.

To reproduce (with a running Splunk)

1. systemctl status splunk
2. observe in green: "Active: active (running)"
3. /opt/splunk/bin/splunk stop
4. systemctl status splunk
5. observe in green is "Active: active (exited)"

So Splunk is still listed as active, though exited.
I've found this ticket at Puppet regarding the active exited state: https://tickets.puppetlabs.com/browse/PUP-7120.
Unfortunately it's a "won't fix" one.

Resolution:
I've changed service.pp to check the Splunk status directly too, by using "splunk status", instead of depending on systemd.

For me the most recent commit fixes the issue after upgrading.
Does it for you?

**Closed** 2017-08-21 09:49 UTC
